---
- hosts:
    - ragnarok
  name: Installs and configure rAthena Server and it's dependencies
  become: true
  tasks:
    - name: Execute APT chores
      ansible.builtin.import_tasks: tasks/apt.yml
      tags:
        - apt
    - name: Install ddclient
      ansible.builtin.import_tasks: tasks/ddclient.yml
      tags:
        - ddclient
    - name: Configure MySQL
      ansible.builtin.import_tasks: tasks/mysql.yml
      tags:
        - mysql
    - name: Install rAthena Server
      ansible.builtin.import_tasks: tasks/rathena.yml
      tags:
        - rathena
