- name: Clone ddclient repository
  ansible.builtin.git:
    repo: "https://github.com/ddclient/ddclient.git"
    dest: "/tmp/ddclient"
    version: "v3.10.0"
  tags:
    - ddclient_clone
- name: Run autogen for ddclient repository
  ansible.builtin.command:
    chdir: "/tmp/ddclient"
    cmd: "./autogen"
    creates: "./configure"
  tags:
    - ddclient_autogen
- name: Run configure for ddclient repository
  ansible.builtin.command:
    chdir: "/tmp/ddclient"
    argv:
      - "./configure"
      - "--prefix=/usr"
      - "--sysconfdir=/etc/ddclient"
      - "--localstatedir=/var"
    creates: "config.status"
  tags:
    - ddclient_configure
- name: Run make for ddclient repository
  ansible.builtin.command:
    chdir: "/tmp/ddclient"
    cmd: "make"
    creates: "ddclient"
  tags:
    - ddclient_make
- name: Install ddclient built binary
  become: true
  ansible.builtin.command:
    chdir: "/tmp/ddclient"
    cmd: "make install"
    creates: "/usr/bin/ddclient"
  tags:
    - ddclient_make_install
- name: Install ddclient configuration
  become: true
  ansible.builtin.template:
    backup: true
    dest: "/etc/ddclient/ddclient.conf"
    src: "templates/ddclient.conf.j2"
    mode: 644
  vars:
    ddclient_conf:
      - protocol: "{{ lookup('ansible.builtin.env', 'ddclient_protocol', default=Undefined) }}"
        login: "{{ lookup('ansible.builtin.env', 'ddclient_login', default=Undefined) }}"
        password: "{{ lookup('ansible.builtin.env', 'ddclient_password', default=Undefined) }}"
        address: "{{ lookup('ansible.builtin.env', 'ddclient_address', default=Undefined) }}"
  tags:
    - ddclient_install_config
- name: Install ddclient systemd unit
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/ddclient/sample-etc_systemd.service"
    dest: "/etc/systemd/system/ddclient.service"
    mode: 644
  tags:
    - ddclient_install_systemd_unit
- name: Enable and start ddclient systemd unit
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: "ddclient"
    state: "started"
  tags:
    - ddclient_start_enable_systemd_unit
