- name: Set rAthena install directory
  ansible.builtin.set_fact:
    rathena_install_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/rathena"
  tags:
    - rathena_facts
- name: Clone rAthena repository
  ansible.builtin.git:
    repo: "https://github.com/rathena/rathena.git"
    dest: "{{ rathena_install_dir }}"
    version: "v3.10.0"
  tags:
    - rathena_clone
- name: Import rAthena MySQL files